# Generated by Django 4.2.4 on 2023-08-04 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_remove_sector_region"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                ("name", models.CharField(max_length=50)),
                ("surname", models.CharField(max_length=50)),
                ("dni", models.CharField(max_length=50, unique=True)),
                ("email", models.EmailField(max_length=100, unique=True)),
                (
                    "role_type",
                    models.CharField(
                        choices=[
                            ("National", "National"),
                            ("Regional", "Regional"),
                            ("District", "District"),
                            ("Sector", "Sector"),
                            ("Standard", "Standard"),
                            ("No appy", "No appy"),
                        ],
                        default="No appy",
                        max_length=50,
                    ),
                ),
                ("observation", models.TextField()),
                ("date_joined", models.DateTimeField(auto_now_add=True)),
                ("last_login", models.DateTimeField(auto_now_add=True)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=False)),
                ("is_superadmin", models.BooleanField(default=False)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.role"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
